import { ThashcatParams } from '../types/THashcat';

export const hashcatParams: ThashcatParams = {
    hashType: 'hash-type',
    attackMode: 'attack-mode',
    session: 'session',
    restore: 'restore',
    runtime: 'runtime',
    outputFormat: 'output-format',
    show: 'show',
    left: 'left',
    potfilePath: 'potfile-path',
    outputFile: 'outfile',
    speedOnly: 'speed-only',
    cpuOnly: 'opencl-device-types=1',
    progressOnly: 'progress-only',
    kernelOptimisation: 'optimized-kernel-enable',
    workloadProfile: 'workload-profile',
    kernelAccel: 'kernel-accel',
    kernelLoops: 'kernel-loops',
    kernelThreads: 'kernel-threads',
    temperatureAbort: 'hwmon-temp-abort',
    rulesFiles: 'rules-file',
    statusJson: 'status-json',
    statusTimer: 'status-timer',
    status: 'status',
    quiet: 'quiet',
    restoreDisable: 'restore-disable',
};
