export const hashTypes = [
   { id: '900', name: 'MD4', description: 'Raw Hash' },
   { id: '0', name: 'MD5', description: 'Raw Hash' },
   { id: '100', name: 'SHA1', description: 'Raw Hash' },
   { id: '1300', name: 'SHA2-224', description: 'Raw Hash' },
   { id: '1400', name: 'SHA2-256', description: 'Raw Hash' },
   { id: '10800', name: 'SHA2-384', description: 'Raw Hash' },
   { id: '1700', name: 'SHA2-512', description: 'Raw Hash' },
   { id: '17300', name: 'SHA3-224', description: 'Raw Hash' },
   { id: '17400', name: 'SHA3-256', description: 'Raw Hash' },
   { id: '17500', name: 'SHA3-384', description: 'Raw Hash' },
   { id: '17600', name: 'SHA3-512', description: 'Raw Hash' },
   { id: '6000', name: 'RIPEMD-160', description: 'Raw Hash' },
   { id: '600', name: 'BLAKE2b-512', description: 'Raw Hash' },
   {
      id: '11700',
      name: 'GOST R 34.11-2012 (Streebog) 256-bit, big-endian',
      description: 'Raw Hash',
   },
   {
      id: '11800',
      name: 'GOST R 34.11-2012 (Streebog) 512-bit, big-endian',
      description: 'Raw Hash',
   },
   { id: '6900', name: 'GOST R 34.11-94', description: 'Raw Hash' },
   {
      id: '17010',
      name: 'GPG (AES-128/AES-256 (SHA-1($pass)))',
      description: 'Raw Hash',
   },
   { id: '5100', name: 'Half MD5', description: 'Raw Hash' },
   { id: '17700', name: 'Keccak-224', description: 'Raw Hash' },
   { id: '17800', name: 'Keccak-256', description: 'Raw Hash' },
   { id: '17900', name: 'Keccak-384', description: 'Raw Hash' },
   { id: '18000', name: 'Keccak-512', description: 'Raw Hash' },
   { id: '6100', name: 'Whirlpool', description: 'Raw Hash' },
   { id: '10100', name: 'SipHash', description: 'Raw Hash' },
   { id: '70', name: 'md5(utf16le($pass))', description: 'Raw Hash' },
   { id: '170', name: 'sha1(utf16le($pass))', description: 'Raw Hash' },
   { id: '1470', name: 'sha256(utf16le($pass))', description: 'Raw Hash' },
   { id: '10870', name: 'sha384(utf16le($pass))', description: 'Raw Hash' },
   { id: '1770', name: 'sha512(utf16le($pass))', description: 'Raw Hash' },
   {
      id: '610',
      name: 'BLAKE2b-512($pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '620',
      name: 'BLAKE2b-512($salt.$pass)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '10',
      name: 'md5($pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '20',
      name: 'md5($salt.$pass)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '3800',
      name: 'md5($salt.$pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '3710',
      name: 'md5($salt.md5($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4110',
      name: 'md5($salt.md5($pass.$salt))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4010',
      name: 'md5($salt.md5($salt.$pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '21300',
      name: 'md5($salt.sha1($salt.$pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '40',
      name: 'md5($salt.utf16le($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '2600',
      name: 'md5(md5($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '3910',
      name: 'md5(md5($pass).md5($salt))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '3500',
      name: 'md5(md5(md5($pass)))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4400',
      name: 'md5(sha1($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4410',
      name: 'md5(sha1($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '20900',
      name: 'md5(sha1($pass).md5($pass).sha1($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '21200',
      name: 'md5(sha1($salt).md5($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4300',
      name: 'md5(strtoupper(md5($pass)))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '30',
      name: 'md5(utf16le($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '110',
      name: 'sha1($pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '120',
      name: 'sha1($salt.$pass)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4900',
      name: 'sha1($salt.$pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4520',
      name: 'sha1($salt.sha1($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '24300',
      name: 'sha1($salt.sha1($pass.$salt))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '140',
      name: 'sha1($salt.utf16le($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '19300',
      name: 'sha1($salt1.$pass.$salt2)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '14400',
      name: 'sha1(CX)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4700',
      name: 'sha1(md5($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4710',
      name: 'sha1(md5($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '21100',
      name: 'sha1(md5($pass.$salt))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '18500',
      name: 'sha1(md5(md5($pass)))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4500',
      name: 'sha1(sha1($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '4510',
      name: 'sha1(sha1($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '5000',
      name: 'sha1(sha1($salt.$pass.$salt))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '130',
      name: 'sha1(utf16le($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1410',
      name: 'sha256($pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1420',
      name: 'sha256($salt.$pass)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '22300',
      name: 'sha256($salt.$pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '20720',
      name: 'sha256($salt.sha256($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '21420',
      name: 'sha256($salt.sha256_bin($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1440',
      name: 'sha256($salt.utf16le($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '20800',
      name: 'sha256(md5($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '20710',
      name: 'sha256(sha256($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '21400',
      name: 'sha256(sha256_bin($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1430',
      name: 'sha256(utf16le($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '10810',
      name: 'sha384($pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '10820',
      name: 'sha384($salt.$pass)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '10840',
      name: 'sha384($salt.utf16le($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '10830',
      name: 'sha384(utf16le($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1710',
      name: 'sha512($pass.$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1720',
      name: 'sha512($salt.$pass)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1740',
      name: 'sha512($salt.utf16le($pass))',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '1730',
      name: 'sha512(utf16le($pass).$salt)',
      description: 'Raw Hash salted and/or iterated',
   },
   {
      id: '50',
      name: 'HMAC-MD5 (key = $pass)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '60',
      name: 'HMAC-MD5 (key = $salt)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '150',
      name: 'HMAC-SHA1 (key = $pass)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '160',
      name: 'HMAC-SHA1 (key = $salt)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '1450',
      name: 'HMAC-SHA256 (key = $pass)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '1460',
      name: 'HMAC-SHA256 (key = $salt)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '1750',
      name: 'HMAC-SHA512 (key = $pass)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '1760',
      name: 'HMAC-SHA512 (key = $salt)',
      description: 'Raw Hash authenticated',
   },
   {
      id: '11750',
      name: 'HMAC-Streebog-256 (key = $pass), big-endian',
      description: 'Raw Hash authenticated',
   },
   {
      id: '11760',
      name: 'HMAC-Streebog-256 (key = $salt), big-endian',
      description: 'Raw Hash authenticated',
   },
   {
      id: '11850',
      name: 'HMAC-Streebog-512 (key = $pass), big-endian',
      description: 'Raw Hash authenticated',
   },
   {
      id: '11860',
      name: 'HMAC-Streebog-512 (key = $salt), big-endian',
      description: 'Raw Hash authenticated',
   },
   {
      id: '28700',
      name: 'Amazon AWS4-HMAC-SHA256',
      description: 'Raw Hash authenticated',
   },
   { id: '11500', name: 'CRC32', description: 'Raw Checksum' },
   { id: '27900', name: 'CRC32C', description: 'Raw Checksum' },
   { id: '28000', name: 'CRC64Jones', description: 'Raw Checksum' },
   {
      id: '18700',
      name: 'Java Object hashCode()',
      description: 'Raw Checksum',
   },
   { id: '25700', name: 'MurmurHash', description: 'Raw Checksum' },
   { id: '27800', name: 'MurmurHash3', description: 'Raw Checksum' },
   {
      id: '14100',
      name: '3DES (PT = $salt, key = $pass)',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   {
      id: '14000',
      name: 'DES (PT = $salt, key = $pass)',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   {
      id: '26401',
      name: 'AES-128-ECB NOKDF (PT = $salt, key = $pass)',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   {
      id: '26402',
      name: 'AES-192-ECB NOKDF (PT = $salt, key = $pass)',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   {
      id: '26403',
      name: 'AES-256-ECB NOKDF (PT = $salt, key = $pass)',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   {
      id: '15400',
      name: 'ChaCha20',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   {
      id: '14500',
      name: 'Linux Kernel Crypto API (2.4)',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   {
      id: '14900',
      name: 'Skip32 (PT = $salt, key = $pass)',
      description: 'Raw Cipher, Known-plaintext attack',
   },
   { id: '11900', name: 'PBKDF2-HMAC-MD5', description: 'Generic KDF' },
   { id: '12000', name: 'PBKDF2-HMAC-SHA1', description: 'Generic KDF' },
   { id: '10900', name: 'PBKDF2-HMAC-SHA256', description: 'Generic KDF' },
   { id: '12100', name: 'PBKDF2-HMAC-SHA512', description: 'Generic KDF' },
   { id: '8900', name: 'scrypt', description: 'Generic KDF' },
   { id: '400', name: 'phpass', description: 'Generic KDF' },
   { id: '16100', name: 'TACACS+', description: 'Network Protocol' },
   {
      id: '11400',
      name: 'SIP digest authentication (MD5)',
      description: 'Network Protocol',
   },
   { id: '5300', name: 'IKE-PSK MD5', description: 'Network Protocol' },
   { id: '5400', name: 'IKE-PSK SHA1', description: 'Network Protocol' },
   {
      id: '25100',
      name: 'SNMPv3 HMAC-MD5-96',
      description: 'Network Protocol',
   },
   {
      id: '25000',
      name: 'SNMPv3 HMAC-MD5-96/HMAC-SHA1-96',
      description: 'Network Protocol',
   },
   {
      id: '25200',
      name: 'SNMPv3 HMAC-SHA1-96',
      description: 'Network Protocol',
   },
   {
      id: '26700',
      name: 'SNMPv3 HMAC-SHA224-128',
      description: 'Network Protocol',
   },
   {
      id: '26800',
      name: 'SNMPv3 HMAC-SHA256-192',
      description: 'Network Protocol',
   },
   {
      id: '26900',
      name: 'SNMPv3 HMAC-SHA384-256',
      description: 'Network Protocol',
   },
   {
      id: '27300',
      name: 'SNMPv3 HMAC-SHA512-384',
      description: 'Network Protocol',
   },
   { id: '2500', name: 'WPA-EAPOL-PBKDF2', description: 'Network Protocol' },
   { id: '2501', name: 'WPA-EAPOL-PMK', description: 'Network Protocol' },
   {
      id: '22000',
      name: 'WPA-PBKDF2-PMKID+EAPOL',
      description: 'Network Protocol',
   },
   {
      id: '22001',
      name: 'WPA-PMK-PMKID+EAPOL',
      description: 'Network Protocol',
   },
   { id: '16800', name: 'WPA-PMKID-PBKDF2', description: 'Network Protocol' },
   { id: '16801', name: 'WPA-PMKID-PMK', description: 'Network Protocol' },
   {
      id: '7300',
      name: 'IPMI2 RAKP HMAC-SHA1',
      description: 'Network Protocol',
   },
   { id: '10200', name: 'CRAM-MD5', description: 'Network Protocol' },
   {
      id: '16500',
      name: 'JWT (JSON Web Token)',
      description: 'Network Protocol',
   },
   { id: '29200', name: 'Radmin3', description: 'Network Protocol' },
   {
      id: '19600',
      name: 'Kerberos 5, etype 17, TGS-REP',
      description: 'Network Protocol',
   },
   {
      id: '19800',
      name: 'Kerberos 5, etype 17, Pre-Auth',
      description: 'Network Protocol',
   },
   {
      id: '28800',
      name: 'Kerberos 5, etype 17, DB',
      description: 'Network Protocol',
   },
   {
      id: '19700',
      name: 'Kerberos 5, etype 18, TGS-REP',
      description: 'Network Protocol',
   },
   {
      id: '19900',
      name: 'Kerberos 5, etype 18, Pre-Auth',
      description: 'Network Protocol',
   },
   {
      id: '28900',
      name: 'Kerberos 5, etype 18, DB',
      description: 'Network Protocol',
   },
   {
      id: '7500',
      name: 'Kerberos 5, etype 23, AS-REQ Pre-Auth',
      description: 'Network Protocol',
   },
   {
      id: '13100',
      name: 'Kerberos 5, etype 23, TGS-REP',
      description: 'Network Protocol',
   },
   {
      id: '18200',
      name: 'Kerberos 5, etype 23, AS-REP',
      description: 'Network Protocol',
   },
   {
      id: '5500',
      name: 'NetNTLMv1 / NetNTLMv1+ESS',
      description: 'Network Protocol',
   },
   {
      id: '27000',
      name: 'NetNTLMv1 / NetNTLMv1+ESS (NT)',
      description: 'Network Protocol',
   },
   { id: '5600', name: 'NetNTLMv2', description: 'Network Protocol' },
   { id: '27100', name: 'NetNTLMv2 (NT)', description: 'Network Protocol' },
   {
      id: '29100',
      name: 'Flask Session Cookie ($salt.$salt.$pass)',
      description: 'Network Protocol',
   },
   {
      id: '4800',
      name: 'iSCSI CHAP authentication, MD5(CHAP)',
      description: 'Network Protocol',
   },
   { id: '8500', name: 'RACF', description: 'Operating System' },
   { id: '6300', name: 'AIX {smd5}', description: 'Operating System' },
   { id: '6700', name: 'AIX {ssha1}', description: 'Operating System' },
   { id: '6400', name: 'AIX {ssha256}', description: 'Operating System' },
   { id: '6500', name: 'AIX {ssha512}', description: 'Operating System' },
   { id: '3000', name: 'LM', description: 'Operating System' },
   {
      id: '19000',
      name: 'QNX /etc/shadow (MD5)',
      description: 'Operating System',
   },
   {
      id: '19100',
      name: 'QNX /etc/shadow (SHA256)',
      description: 'Operating System',
   },
   {
      id: '19200',
      name: 'QNX /etc/shadow (SHA512)',
      description: 'Operating System',
   },
   {
      id: '15300',
      name: 'DPAPI masterkey file v1 (context 1 and 2)',
      description: 'Operating System',
   },
   {
      id: '15310',
      name: 'DPAPI masterkey file v1 (context 3)',
      description: 'Operating System',
   },
   {
      id: '15900',
      name: 'DPAPI masterkey file v2 (context 1 and 2)',
      description: 'Operating System',
   },
   {
      id: '15910',
      name: 'DPAPI masterkey file v2 (context 3)',
      description: 'Operating System',
   },
   { id: '7200', name: 'GRUB 2', description: 'Operating System' },
   {
      id: '12800',
      name: 'MS-AzureSync PBKDF2-HMAC-SHA256',
      description: 'Operating System',
   },
   {
      id: '12400',
      name: 'BSDi Crypt, Extended DES',
      description: 'Operating System',
   },
   { id: '1000', name: 'NTLM', description: 'Operating System' },
   { id: '9900', name: 'Radmin2', description: 'Operating System' },
   {
      id: '5800',
      name: 'Samsung Android Password/PIN',
      description: 'Operating System',
   },
   {
      id: '28100',
      name: 'Windows Hello PIN/Password',
      description: 'Operating System',
   },
   {
      id: '13800',
      name: 'Windows Phone 8+ PIN/password',
      description: 'Operating System',
   },
   { id: '2410', name: 'Cisco-ASA MD5', description: 'Operating System' },
   {
      id: '9200',
      name: 'Cisco-IOS $8$ (PBKDF2-SHA256)',
      description: 'Operating System',
   },
   {
      id: '9300',
      name: 'Cisco-IOS $9$ (scrypt)',
      description: 'Operating System',
   },
   {
      id: '5700',
      name: 'Cisco-IOS type 4 (SHA256)',
      description: 'Operating System',
   },
   { id: '2400', name: 'Cisco-PIX MD5', description: 'Operating System' },
   {
      id: '8100',
      name: 'Citrix NetScaler (SHA1)',
      description: 'Operating System',
   },
   {
      id: '22200',
      name: 'Citrix NetScaler (SHA512)',
      description: 'Operating System',
   },
   {
      id: '1100',
      name: 'Domain Cached Credentials (DCC), MS Cache',
      description: 'Operating System',
   },
   {
      id: '2100',
      name: 'Domain Cached Credentials 2 (DCC2), MS Cache 2',
      description: 'Operating System',
   },
   {
      id: '7000',
      name: 'FortiGate (FortiOS)',
      description: 'Operating System',
   },
   {
      id: '26300',
      name: 'FortiGate256 (FortiOS256)',
      description: 'Operating System',
   },
   { id: '125', name: 'ArubaOS', description: 'Operating System' },
   { id: '501', name: 'Juniper IVE', description: 'Operating System' },
   {
      id: '22',
      name: 'Juniper NetScreen/SSG (ScreenOS)',
      description: 'Operating System',
   },
   {
      id: '15100',
      name: 'Juniper/NetBSD sha1crypt',
      description: 'Operating System',
   },
   {
      id: '26500',
      name: 'iPhone passcode (UID key + System Keybag)',
      description: 'Operating System',
   },
   {
      id: '122',
      name: 'macOS v10.4, macOS v10.5, macOS v10.6',
      description: 'Operating System',
   },
   { id: '1722', name: 'macOS v10.7', description: 'Operating System' },
   {
      id: '7100',
      name: 'macOS v10.8+ (PBKDF2-SHA512)',
      description: 'Operating System',
   },
   {
      id: '3200',
      name: 'bcrypt $2*$, Blowfish (Unix)',
      description: 'Operating System',
   },
   {
      id: '500',
      name: 'md5crypt, MD5 (Unix), Cisco-IOS $1$ (MD5)',
      description: 'Operating System',
   },
   {
      id: '1500',
      name: 'descrypt, DES (Unix), Traditional DES',
      description: 'Operating System',
   },
   {
      id: '29000',
      name: "sha1($salt.sha1(utf16le($username).':'.utf16le($pass)))",
      description: 'Operating System',
   },
   {
      id: '7400',
      name: 'sha256crypt $5$, SHA256 (Unix)',
      description: 'Operating System',
   },
   {
      id: '1800',
      name: 'sha512crypt $6$, SHA512 (Unix)',
      description: 'Operating System',
   },
   { id: '24600', name: 'SQLCipher', description: 'Database Server' },
   { id: '131', name: 'MSSQL (2000)', description: 'Database Server' },
   { id: '132', name: 'MSSQL (2005)', description: 'Database Server' },
   { id: '1731', name: 'MSSQL (2012, 2014)', description: 'Database Server' },
   {
      id: '24100',
      name: 'MongoDB ServerKey SCRAM-SHA-1',
      description: 'Database Server',
   },
   {
      id: '24200',
      name: 'MongoDB ServerKey SCRAM-SHA-256',
      description: 'Database Server',
   },
   { id: '12', name: 'PostgreSQL', description: 'Database Server' },
   {
      id: '11100',
      name: 'PostgreSQL CRAM (MD5)',
      description: 'Database Server',
   },
   {
      id: '28600',
      name: 'PostgreSQL SCRAM-SHA-256',
      description: 'Database Server',
   },
   {
      id: '3100',
      name: 'Oracle H: Type (Oracle 7+)',
      description: 'Database Server',
   },
   {
      id: '112',
      name: 'Oracle S: Type (Oracle 11+)',
      description: 'Database Server',
   },
   {
      id: '12300',
      name: 'Oracle T: Type (Oracle 12+)',
      description: 'Database Server',
   },
   {
      id: '7401',
      name: 'MySQL $A$ (sha256crypt)',
      description: 'Database Server',
   },
   { id: '11200', name: 'MySQL CRAM (SHA1)', description: 'Database Server' },
   { id: '200', name: 'MySQL323', description: 'Database Server' },
   { id: '300', name: 'MySQL4.1/MySQL5', description: 'Database Server' },
   { id: '8000', name: 'Sybase ASE', description: 'Database Server' },
   {
      id: '8300',
      name: 'DNSSEC (NSEC3)',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '25900',
      name: 'KNX IP Secure - Device Authentication Code',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '16400',
      name: 'CRAM-MD5 Dovecot',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '1411',
      name: 'SSHA-256(Base64), LDAP {SSHA256}',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '1711',
      name: 'SSHA-512(Base64), LDAP {SSHA512}',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '24900',
      name: 'Dahua Authentication MD5',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '10901',
      name: 'RedHat 389-DS LDAP (PBKDF2-HMAC-SHA256)',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '15000',
      name: 'FileZilla Server >= 0.9.55',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '12600',
      name: 'ColdFusion 10+',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '1600',
      name: 'Apache $apr1$ MD5, md5apr1, MD5 (APR)',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '141',
      name: 'Episerver 6.x < .NET 4',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '1441',
      name: 'Episerver 6.x >= .NET 4',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '1421',
      name: 'hMailServer',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '101',
      name: 'nsldap, SHA-1(Base64), Netscape LDAP SHA',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '111',
      name: 'nsldaps, SSHA-1(Base64), Netscape LDAP SSHA',
      description: 'FTP, HTTP, SMTP, LDAP Server',
   },
   {
      id: '7700',
      name: 'SAP CODVN B (BCODE)',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '7701',
      name: 'SAP CODVN B (BCODE) from RFC_READ_TABLE',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '7800',
      name: 'SAP CODVN F/G (PASSCODE)',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '7801',
      name: 'SAP CODVN F/G (PASSCODE) from RFC_READ_TABLE',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '10300',
      name: 'SAP CODVN H (PWDSALTEDHASH) iSSHA-1',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '133',
      name: 'PeopleSoft',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '13500',
      name: 'PeopleSoft PS_TOKEN',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '21500',
      name: 'SolarWinds Orion',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '21501',
      name: 'SolarWinds Orion v2',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '24',
      name: 'SolarWinds Serv-U',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '8600',
      name: 'Lotus Notes/Domino 5',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '8700',
      name: 'Lotus Notes/Domino 6',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '9100',
      name: 'Lotus Notes/Domino 8',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '26200',
      name: 'OpenEdge Progress Encode',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '20600',
      name: 'Oracle Transportation Management (SHA256)',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '4711',
      name: 'Huawei sha1(md5($pass).$salt)',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '20711',
      name: 'AuthMe sha256',
      description: 'Enterprise Application Software (EAS)',
   },
   {
      id: '22400',
      name: 'AES Crypt (SHA256)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '27400',
      name: 'VMware VMX (PBKDF2-HMAC-SHA1 + AES-256-CBC)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '14600',
      name: 'LUKS v1 (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29541',
      name: 'LUKS v1 RIPEMD-160 + AES',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29542',
      name: 'LUKS v1 RIPEMD-160 + Serpent',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29543',
      name: 'LUKS v1 RIPEMD-160 + Twofish',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29511',
      name: 'LUKS v1 SHA-1 + AES',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29512',
      name: 'LUKS v1 SHA-1 + Serpent',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29513',
      name: 'LUKS v1 SHA-1 + Twofish',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29521',
      name: 'LUKS v1 SHA-256 + AES',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29522',
      name: 'LUKS v1 SHA-256 + Serpent',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29523',
      name: 'LUKS v1 SHA-256 + Twofish',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29531',
      name: 'LUKS v1 SHA-512 + AES',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29532',
      name: 'LUKS v1 SHA-512 + Serpent',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29533',
      name: 'LUKS v1 SHA-512 + Twofish',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13711',
      name: 'VeraCrypt RIPEMD160 + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13712',
      name: 'VeraCrypt RIPEMD160 + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13713',
      name: 'VeraCrypt RIPEMD160 + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13741',
      name: 'VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13742',
      name: 'VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13743',
      name: 'VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29411',
      name: 'VeraCrypt RIPEMD160 + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29412',
      name: 'VeraCrypt RIPEMD160 + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29413',
      name: 'VeraCrypt RIPEMD160 + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29441',
      name: 'VeraCrypt RIPEMD160 + XTS 512 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29442',
      name: 'VeraCrypt RIPEMD160 + XTS 1024 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29443',
      name: 'VeraCrypt RIPEMD160 + XTS 1536 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13751',
      name: 'VeraCrypt SHA256 + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13752',
      name: 'VeraCrypt SHA256 + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13753',
      name: 'VeraCrypt SHA256 + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13761',
      name: 'VeraCrypt SHA256 + XTS 512 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13762',
      name: 'VeraCrypt SHA256 + XTS 1024 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13763',
      name: 'VeraCrypt SHA256 + XTS 1536 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29451',
      name: 'VeraCrypt SHA256 + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29452',
      name: 'VeraCrypt SHA256 + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29453',
      name: 'VeraCrypt SHA256 + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29461',
      name: 'VeraCrypt SHA256 + XTS 512 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29462',
      name: 'VeraCrypt SHA256 + XTS 1024 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29463',
      name: 'VeraCrypt SHA256 + XTS 1536 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13721',
      name: 'VeraCrypt SHA512 + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13722',
      name: 'VeraCrypt SHA512 + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13723',
      name: 'VeraCrypt SHA512 + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29421',
      name: 'VeraCrypt SHA512 + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29422',
      name: 'VeraCrypt SHA512 + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29423',
      name: 'VeraCrypt SHA512 + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13771',
      name: 'VeraCrypt Streebog-512 + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13772',
      name: 'VeraCrypt Streebog-512 + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13773',
      name: 'VeraCrypt Streebog-512 + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13781',
      name: 'VeraCrypt Streebog-512 + XTS 512 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13782',
      name: 'VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13783',
      name: 'VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29471',
      name: 'VeraCrypt Streebog-512 + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29472',
      name: 'VeraCrypt Streebog-512 + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29473',
      name: 'VeraCrypt Streebog-512 + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29481',
      name: 'VeraCrypt Streebog-512 + XTS 512 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29482',
      name: 'VeraCrypt Streebog-512 + XTS 1024 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29483',
      name: 'VeraCrypt Streebog-512 + XTS 1536 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13731',
      name: 'VeraCrypt Whirlpool + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13732',
      name: 'VeraCrypt Whirlpool + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '13733',
      name: 'VeraCrypt Whirlpool + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29431',
      name: 'VeraCrypt Whirlpool + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29432',
      name: 'VeraCrypt Whirlpool + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29433',
      name: 'VeraCrypt Whirlpool + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '23900',
      name: 'BestCrypt v3 Volume Encryption',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '16700',
      name: 'FileVault 2',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '27500',
      name: 'VirtualBox (PBKDF2-HMAC-SHA256 & AES-128-XTS)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '27600',
      name: 'VirtualBox (PBKDF2-HMAC-SHA256 & AES-256-XTS)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '20011',
      name: 'DiskCryptor SHA512 + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '20012',
      name: 'DiskCryptor SHA512 + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '20013',
      name: 'DiskCryptor SHA512 + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '22100',
      name: 'BitLocker',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '12900',
      name: 'Android FDE (Samsung DEK)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '8800',
      name: 'Android FDE <= 4.3',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '18300',
      name: 'Apple File System (APFS)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6211',
      name: 'TrueCrypt RIPEMD160 + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6212',
      name: 'TrueCrypt RIPEMD160 + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6213',
      name: 'TrueCrypt RIPEMD160 + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6241',
      name: 'TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6242',
      name: 'TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6243',
      name: 'TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29311',
      name: 'TrueCrypt RIPEMD160 + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29312',
      name: 'TrueCrypt RIPEMD160 + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29313',
      name: 'TrueCrypt RIPEMD160 + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29341',
      name: 'TrueCrypt RIPEMD160 + XTS 512 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29342',
      name: 'TrueCrypt RIPEMD160 + XTS 1024 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29343',
      name: 'TrueCrypt RIPEMD160 + XTS 1536 bit + boot-mode',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6221',
      name: 'TrueCrypt SHA512 + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6222',
      name: 'TrueCrypt SHA512 + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6223',
      name: 'TrueCrypt SHA512 + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29321',
      name: 'TrueCrypt SHA512 + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29322',
      name: 'TrueCrypt SHA512 + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29323',
      name: 'TrueCrypt SHA512 + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6231',
      name: 'TrueCrypt Whirlpool + XTS 512 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6232',
      name: 'TrueCrypt Whirlpool + XTS 1024 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '6233',
      name: 'TrueCrypt Whirlpool + XTS 1536 bit (legacy)',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29331',
      name: 'TrueCrypt Whirlpool + XTS 512 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29332',
      name: 'TrueCrypt Whirlpool + XTS 1024 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '29333',
      name: 'TrueCrypt Whirlpool + XTS 1536 bit',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '12200',
      name: 'eCryptfs',
      description: 'Full-Disk Encryption (FDE)',
   },
   {
      id: '10400',
      name: 'PDF 1.1 - 1.3 (Acrobat 2 - 4)',
      description: 'Document',
   },
   {
      id: '10410',
      name: 'PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #1',
      description: 'Document',
   },
   {
      id: '10420',
      name: 'PDF 1.1 - 1.3 (Acrobat 2 - 4), collider #2',
      description: 'Document',
   },
   {
      id: '10500',
      name: 'PDF 1.4 - 1.6 (Acrobat 5 - 8)',
      description: 'Document',
   },
   {
      id: '25400',
      name: 'PDF 1.4 - 1.6 (Acrobat 5 - 8) - user and owner pass',
      description: 'Document',
   },
   {
      id: '10600',
      name: 'PDF 1.7 Level 3 (Acrobat 9)',
      description: 'Document',
   },
   {
      id: '10700',
      name: 'PDF 1.7 Level 8 (Acrobat 10 - 11)',
      description: 'Document',
   },
   { id: '9400', name: 'MS Office 2007', description: 'Document' },
   { id: '9500', name: 'MS Office 2010', description: 'Document' },
   { id: '9600', name: 'MS Office 2013', description: 'Document' },
   {
      id: '25300',
      name: 'MS Office 2016 - SheetProtection',
      description: 'Document',
   },
   {
      id: '9700',
      name: 'MS Office <= 2003 $0/$1, MD5 + RC4',
      description: 'Document',
   },
   {
      id: '9710',
      name: 'MS Office <= 2003 $0/$1, MD5 + RC4, collider #1',
      description: 'Document',
   },
   {
      id: '9720',
      name: 'MS Office <= 2003 $0/$1, MD5 + RC4, collider #2',
      description: 'Document',
   },
   {
      id: '9810',
      name: 'MS Office <= 2003 $3, SHA1 + RC4, collider #1',
      description: 'Document',
   },
   {
      id: '9820',
      name: 'MS Office <= 2003 $3, SHA1 + RC4, collider #2',
      description: 'Document',
   },
   {
      id: '9800',
      name: 'MS Office <= 2003 $3/$4, SHA1 + RC4',
      description: 'Document',
   },
   {
      id: '18400',
      name: 'Open Document Format (ODF) 1.2 (SHA-256, AES)',
      description: 'Document',
   },
   {
      id: '18600',
      name: 'Open Document Format (ODF) 1.1 (SHA-1, Blowfish)',
      description: 'Document',
   },
   { id: '16200', name: 'Apple Secure Notes', description: 'Document' },
   { id: '23300', name: 'Apple iWork', description: 'Document' },
   {
      id: '6600',
      name: '1Password, agilekeychain',
      description: 'Password Manager',
   },
   {
      id: '8200',
      name: '1Password, cloudkeychain',
      description: 'Password Manager',
   },
   { id: '9000', name: 'Password Safe v2', description: 'Password Manager' },
   { id: '5200', name: 'Password Safe v3', description: 'Password Manager' },
   {
      id: '6800',
      name: 'LastPass + LastPass sniffed',
      description: 'Password Manager',
   },
   {
      id: '13400',
      name: 'KeePass 1 (AES/Twofish) and KeePass 2 (AES)',
      description: 'Password Manager',
   },
   {
      id: '29700',
      name: 'KeePass 1 (AES/Twofish) and KeePass 2 (AES) - keyfile only mode',
      description: 'Password Manager',
   },
   { id: '23400', name: 'Bitwarden', description: 'Password Manager' },
   { id: '16900', name: 'Ansible Vault', description: 'Password Manager' },
   { id: '26000', name: 'Mozilla key3.db', description: 'Password Manager' },
   { id: '26100', name: 'Mozilla key4.db', description: 'Password Manager' },
   { id: '23100', name: 'Apple Keychain', description: 'Password Manager' },
   { id: '11600', name: '7-Zip', description: 'Archive' },
   { id: '12500', name: 'RAR3-hp', description: 'Archive' },
   { id: '23800', name: 'RAR3-p (Compressed)', description: 'Archive' },
   { id: '23700', name: 'RAR3-p (Uncompressed)', description: 'Archive' },
   { id: '13000', name: 'RAR5', description: 'Archive' },
   {
      id: '17220',
      name: 'PKZIP (Compressed Multi-File)',
      description: 'Archive',
   },
   { id: '17200', name: 'PKZIP (Compressed)', description: 'Archive' },
   { id: '17225', name: 'PKZIP (Mixed Multi-File)', description: 'Archive' },
   {
      id: '17230',
      name: 'PKZIP (Mixed Multi-File Checksum-Only)',
      description: 'Archive',
   },
   { id: '17210', name: 'PKZIP (Uncompressed)', description: 'Archive' },
   { id: '20500', name: 'PKZIP Master Key', description: 'Archive' },
   {
      id: '20510',
      name: 'PKZIP Master Key (6 byte optimization)',
      description: 'Archive',
   },
   { id: '23001', name: 'SecureZIP AES-128', description: 'Archive' },
   { id: '23002', name: 'SecureZIP AES-192', description: 'Archive' },
   { id: '23003', name: 'SecureZIP AES-256', description: 'Archive' },
   { id: '13600', name: 'WinZip', description: 'Archive' },
   { id: '18900', name: 'Android Backup', description: 'Archive' },
   { id: '24700', name: 'Stuffit5', description: 'Archive' },
   { id: '13200', name: 'AxCrypt 1', description: 'Archive' },
   { id: '13300', name: 'AxCrypt 1 in-memory SHA1', description: 'Archive' },
   { id: '23500', name: 'AxCrypt 2 AES-128', description: 'Archive' },
   { id: '23600', name: 'AxCrypt 2 AES-256', description: 'Archive' },
   { id: '14700', name: 'iTunes backup < 10.0', description: 'Archive' },
   { id: '14800', name: 'iTunes backup >= 10.0', description: 'Archive' },
   {
      id: '8400',
      name: 'WBB3 (Woltlab Burning Board)',
      description: 'Forums, CMS, E-Commerce',
   },
   { id: '2612', name: 'PHPS', description: 'Forums, CMS, E-Commerce' },
   {
      id: '121',
      name: 'SMF (Simple Machines Forum) > v1.1',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '3711',
      name: 'MediaWiki B type',
      description: 'Forums, CMS, E-Commerce',
   },
   { id: '4521', name: 'Redmine', description: 'Forums, CMS, E-Commerce' },
   {
      id: '24800',
      name: 'Umbraco HMAC-SHA1',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '11',
      name: 'Joomla < 2.5.18',
      description: 'Forums, CMS, E-Commerce',
   },
   { id: '13900', name: 'OpenCart', description: 'Forums, CMS, E-Commerce' },
   { id: '11000', name: 'PrestaShop', description: 'Forums, CMS, E-Commerce' },
   { id: '16000', name: 'Tripcode', description: 'Forums, CMS, E-Commerce' },
   { id: '7900', name: 'Drupal7', description: 'Forums, CMS, E-Commerce' },
   { id: '4522', name: 'PunBB', description: 'Forums, CMS, E-Commerce' },
   {
      id: '2811',
      name: 'MyBB 1.2+, IPB2+ (Invision Power Board)',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '2611',
      name: 'vBulletin < v3.8.5',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '2711',
      name: 'vBulletin >= v3.8.5',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '25600',
      name: 'bcrypt(md5($pass)) / bcryptmd5',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '25800',
      name: 'bcrypt(sha1($pass)) / bcryptsha1',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '28400',
      name: 'bcrypt(sha512($pass)) / bcryptsha512',
      description: 'Forums, CMS, E-Commerce',
   },
   {
      id: '21',
      name: 'osCommerce, xt:Commerce',
      description: 'Forums, CMS, E-Commerce',
   },
   { id: '18100', name: 'TOTP (HMAC-SHA1)', description: 'One-Time Password' },
   { id: '2000', name: 'STDOUT', description: 'Plaintext' },
   { id: '99999', name: 'Plaintext', description: 'Plaintext' },
   { id: '21600', name: 'Web2py pbkdf2-sha512', description: 'Framework' },
   { id: '10000', name: 'Django (PBKDF2-SHA256)', description: 'Framework' },
   { id: '124', name: 'Django (SHA-1)', description: 'Framework' },
   {
      id: '12001',
      name: 'Atlassian (PBKDF2-HMAC-SHA1)',
      description: 'Framework',
   },
   {
      id: '19500',
      name: 'Ruby on Rails Restful-Authentication',
      description: 'Framework',
   },
   {
      id: '27200',
      name: 'Ruby on Rails Restful Auth (one round, no sitekey)',
      description: 'Framework',
   },
   {
      id: '30000',
      name: 'Python Werkzeug MD5 (HMAC-MD5 (key = $salt))',
      description: 'Framework',
   },
   {
      id: '30120',
      name: 'Python Werkzeug SHA256 (HMAC-SHA256 (key = $salt))',
      description: 'Framework',
   },
   {
      id: '20200',
      name: 'Python passlib pbkdf2-sha512',
      description: 'Framework',
   },
   {
      id: '20300',
      name: 'Python passlib pbkdf2-sha256',
      description: 'Framework',
   },
   {
      id: '20400',
      name: 'Python passlib pbkdf2-sha1',
      description: 'Framework',
   },
   {
      id: '24410',
      name: 'PKCS#8 Private Keys (PBKDF2-HMAC-SHA1 + 3DES/AES)',
      description: 'Private Key',
   },
   {
      id: '24420',
      name: 'PKCS#8 Private Keys (PBKDF2-HMAC-SHA256 + 3DES/AES)',
      description: 'Private Key',
   },
   {
      id: '15500',
      name: 'JKS Java Key Store Private Keys (SHA1)',
      description: 'Private Key',
   },
   {
      id: '22911',
      name: 'RSA/DSA/EC/OpenSSH Private Keys ($0$)',
      description: 'Private Key',
   },
   {
      id: '22921',
      name: 'RSA/DSA/EC/OpenSSH Private Keys ($6$)',
      description: 'Private Key',
   },
   {
      id: '22931',
      name: 'RSA/DSA/EC/OpenSSH Private Keys ($1, $3$)',
      description: 'Private Key',
   },
   {
      id: '22941',
      name: 'RSA/DSA/EC/OpenSSH Private Keys ($4$)',
      description: 'Private Key',
   },
   {
      id: '22951',
      name: 'RSA/DSA/EC/OpenSSH Private Keys ($5$)',
      description: 'Private Key',
   },
   {
      id: '23200',
      name: 'XMPP SCRAM PBKDF2-SHA1',
      description: 'Instant Messaging Service',
   },
   {
      id: '28300',
      name: 'Teamspeak 3 (channel hash)',
      description: 'Instant Messaging Service',
   },
   {
      id: '22600',
      name: 'Telegram Desktop < v2.1.14 (PBKDF2-HMAC-SHA1)',
      description: 'Instant Messaging Service',
   },
   {
      id: '24500',
      name: 'Telegram Desktop >= v2.1.14 (PBKDF2-HMAC-SHA512)',
      description: 'Instant Messaging Service',
   },
   {
      id: '22301',
      name: 'Telegram Mobile App Passcode (SHA256)',
      description: 'Instant Messaging Service',
   },
   { id: '23', name: 'Skype', description: 'Instant Messaging Service' },
   {
      id: '29600',
      name: 'Terra Station Wallet (AES256-CBC(PBKDF2($pass)))',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '26600',
      name: 'MetaMask Wallet',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '21000',
      name: 'BitShares v0.x - sha512(sha512_bin(pass))',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '28501',
      name: 'Bitcoin WIF private key (P2PKH), compressed',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '28502',
      name: 'Bitcoin WIF private key (P2PKH), uncompressed',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '28503',
      name: 'Bitcoin WIF private key (P2WPKH, Bech32), compressed',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '28504',
      name: 'Bitcoin WIF private key (P2WPKH, Bech32), uncompressed',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '28505',
      name: 'Bitcoin WIF private key (P2SH(P2WPKH)), compressed',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '28506',
      name: 'Bitcoin WIF private key (P2SH(P2WPKH)), uncompressed',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '11300',
      name: 'Bitcoin/Litecoin wallet.dat',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '16600',
      name: 'Electrum Wallet (Salt-Type 1-3)',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '21700',
      name: 'Electrum Wallet (Salt-Type 4)',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '21800',
      name: 'Electrum Wallet (Salt-Type 5)',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '12700',
      name: 'Blockchain, My Wallet',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '15200',
      name: 'Blockchain, My Wallet, V2',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '18800',
      name: 'Blockchain, My Wallet, Second Password (SHA256)',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '25500',
      name: 'Stargazer Stellar Wallet XLM',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '16300',
      name: 'Ethereum Pre-Sale Wallet, PBKDF2-HMAC-SHA256',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '15600',
      name: 'Ethereum Wallet, PBKDF2-HMAC-SHA256',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '15700',
      name: 'Ethereum Wallet, SCRYPT',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '22500',
      name: 'MultiBit Classic .key (MD5)',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '27700',
      name: 'MultiBit Classic .wallet (scrypt)',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '22700',
      name: 'MultiBit HD (scrypt)',
      description: 'Cryptocurrency Wallet',
   },
   {
      id: '28200',
      name: 'Exodus Desktop Wallet (scrypt)',
      description: 'Cryptocurrency Wallet',
   },
];
