version: '3.9'
services:

  mysql:
    image: "mysql:8.0.30"
    container_name: ${DB_ENDPOINT}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - hashkitty-storage:/var/lib/mysql
      - ../hashkitty-server/sqldump:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${DB_ENDPOINT}
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    networks:
      - backend
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80

  hashkitty-back:
    container_name: hashkitty-back
    restart: always
    build:
      context: '../hashkitty-server/'
      args:
        PORT: ${API_PORT}
    environment:
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      WORDLISTS_DIR_PATH: ${WORDLISTS_DIR_PATH}
    volumes:
      - ../hashkitty-server:/app
      - hashkitty-wordlists:${WORDLISTS_DIR_PATH}
    networks:
      - backend
      - frontend
    depends_on:
      - mysql
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  hashkitty-front:
    container_name: hashkitty-front
    build:
      context: '../hashkitty-front/'
      args:
        API_ENDPOINT: ${API_ENDPOINT}
        API_PORT: ${API_PORT}
    environment:
      PORT: 80
    networks:
      - frontend
    depends_on:
      - hashkitty-back
    restart: always
    ports:
      - ${WEB_FRONT_PORT}:80
    volumes:
      - ../hashkitty-front:/app

networks:
  frontend:
  backend:

volumes:
  hashkitty-storage:
  hashkitty-wordlists: