version: '3.9'
services:

  mysql:
    image: "mysql:8.0.30"
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "hashkitty"
      MYSQL_PASSWORD: "hashkitty"
      MYSQL_DATABASE: "hashkitty"
    networks:
      - backend
    volumes:
      - hashkitty-storage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    networks:
      - backend
    restart: always
    ports:
      - 8080:80
  
  hashkitty-back:
    build:
      context: '../hashkitty-server/'
    networks:
      - backend
      - frontend
    depends_on:
      - mysql
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always
    container_name: hashkitty-back

  hashkitty-front:
    build:
      context: '../hashkitty-front/'
    networks:
      - frontend
    depends_on:
      - hashkitty-back
    restart: always
    ports:
    - 3000:3000
    container_name: hashkitty-front
  

networks:
  frontend:
  backend:

volumes:
  hashkitty-storage: