FROM node:18.12.1-alpine3.16
ENV PROJECT=/app
WORKDIR ${PROJECT}
COPY package.json tsconfig.json ${PROJECT}/
COPY src/ ${PROJECT}/src/
RUN npm i
RUN npm run compile
EXPOSE 1337
CMD node ${PROJECT}/build/src/index.js
