# syntax = docker/dockerfile:1.4

FROM node:hydrogen-slim

WORKDIR /app
COPY src/ /app/src/
COPY public /app/public/
COPY \
    package.json \
    package-lock.json \
    tsconfig.json \
    tsconfig.node.json \
    custom.d.ts index.html \
    vite.config.ts \
    postcss.config.cjs \
    tailwind.config.cjs /app/
RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm
RUN npm ci

ARG API_ENDPOINT
ARG API_PORT
ENV VITE_API_ENDPOINT $API_ENDPOINT
ENV VITE_APP_API_PORT $API_PORT

EXPOSE $PORT
CMD npm run dev