# syntax = docker/dockerfile:1.4

FROM node:hydrogen-slim

WORKDIR /app
COPY src/ /app/src/
COPY public /app/public/
COPY \
    docker/.env \
    package.json \
    package-lock.json \
    tsconfig.json \
    tsconfig.node.json \
    custom.d.ts index.html \
    vite.config.ts \
    postcss.config.cjs \
    tailwind.config.cjs /app/
RUN --mount=type=cache,target=/usr/src/app/.npm \
    npm set cache /usr/src/app/.npm
RUN npm ci

CMD npm run dev -- --host